services:
  db:
    image: postgres
    restart: always
    container_name: GT-Chef
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/gtchef

volumes:
  data:
